directories:
  output: release
  buildResources: build
appId: com.docbuddy.app
productName: Doc-Buddy
copyright: Copyright © 2025
files:
  - filter:
      - dist-electron
      - dist-react
      - package.json
      - '!**/.vscode/*'
      - '!src/*'
      - '!electron/*'
      - '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc,dev-app-update.yml,CHANGELOG.md}'
      - '!{.env,.env.*,.npmrc,pnpm-lock.yaml}'
      - '!{tsconfig.json,tsconfig.node.json,vite.config.ts,electron.vite.config.ts}'
mac:
  category: public.app-category.developer-tools
  hardenedRuntime: true
  gatekeeperAssess: false
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: build/icon.icns
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: build/icon.ico
linux:
  target:
    - AppImage
    - deb
  category: Development
  icon: build/icon.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: always
publish:
  provider: github
  releaseType: release
electronVersion: 28.3.3
